DROP TABLE IF EXISTS users;
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL CHECK ( username <> '' ),
    email      VARCHAR(100) NOT NULL UNIQUE CHECK ( email <> '' ),
    age        INTEGER CHECK ( age > 0 ),
    status     VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP

);
INSERT INTO users (username, email, age)
VALUES ('Ann', 'signoraann@gmail.com', 19);
INSERT INTO users (username, age)
VALUES ('Ben', 23); --this row is broken by purpose
INSERT INTO users (username, email, age)
VALUES ('Nastya', '', 9); --this row is broken by purpose
INSERT INTO users (username, email, age)
VALUES ('Olga', 'hatters@mail.com', 69);
INSERT INTO users (username, email, age)
VALUES ('Polina', 'hatters@mail.com', 29); --that duplicates are blocked by purpose
INSERT INTO users (username, email, age)
VALUES ('Pavel', 'pashka@hmail.com', 30);
INSERT INTO users (username, email, age, status)
VALUES ('Roman', 'chamomile@mail.com', 20, '123456789123456789123'); --this row is broken by purpose
INSERT INTO users (username, email, age)
VALUES ('', 'empty@hmail.com', 21); --this row is broken by purpose
INSERT INTO users (email, age)
VALUES ('null@hmail.com', 34); --this row is broken by purpose