DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL CHECK ( username <> '' ),
    email      VARCHAR(100) NOT NULL UNIQUE CHECK ( email <> '' ),
    age        INTEGER CHECK ( age > 0 ),
    status     VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE posts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    post_title VARCHAR(100) NOT NULL CHECK (post_title <> ''),
    content    TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);