DROP TABLE IF EXISTS bank_account;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL CHECK ( username <> '' ),
    email      VARCHAR(100) NOT NULL UNIQUE CHECK ( email <> '' ),
    age        INTEGER CHECK ( age > 0 ),
    status     VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE posts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    post_title VARCHAR(100) NOT NULL CHECK (post_title <> ''),
    content    TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE addresses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    city       VARCHAR(170) NOT NULL CHECK ( city <> '' ),
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT unique_user_city UNIQUE (user_id, city)
);

CREATE TABLE bank_account
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name VARCHAR(20)      NOT NULL CHECK (account_name <> ''),
    balance      DOUBLE PRECISION NOT NULL CHECK ( balance >= 0 ),
    created_at   TIMESTAMPTZ DEFAULT now()
)

