package com.signoraann.javalearning.lesson30;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.math.BigDecimal;
import java.sql.*;

class BankServiceTest {
    private Connection connection;
    private BankDaoJdbc bankDao;

    @BeforeEach
    void createTestBase() throws SQLException {
        connection = DriverManager.getConnection("jdbc:h2:mem:bank_test;DB_CLOSE_DELAY=-1");
        bankDao = new BankDaoJdbc();
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    DROP TABLE IF EXISTS bank_account;
                    CREATE TABLE bank_account
                    (
                        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        account_name VARCHAR(20)   UNIQUE  NOT NULL CHECK (account_name <> ''),
                        balance DECIMAL(19,2) NOT NULL CHECK ( balance >= 0 ),
                        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                    );
                    INSERT INTO bank_account (account_name, balance) VALUES ('A', 100.00), ('B', 0.00);
                    """);
        }
    }

    @AfterEach
    void closeResources() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }

    @Test
    void testTransferMoneyTwiceHappyPath() {
        BankService bankService = new BankService(bankDao);
        bankService.transferMoney(connection, "A", "B", new BigDecimal("25.50"));
        bankService.transferMoney(connection, "A", "B", new BigDecimal("25.50"));
        assertEquals(new BigDecimal("49.00"), bankDao.getBalance(connection, "A"));
        assertEquals(new BigDecimal("51.00"), bankDao.getBalance(connection, "B"));
    }

    @Test
    void testTransferMoneyRollsBackWhenDepositFails() {
        BankDao brokenBankDao = new BankDaoJdbc() {
            @Override
            public void deposit(Connection connection, String accountName, BigDecimal amount) {
                throw new BankException("Simulated deposit failure");
            }
        };
        BankService bankService = new BankService(brokenBankDao);
        assertThrows(BankException.class, () -> bankService.transferMoney(connection, "A", "B", new BigDecimal("10.00")));
        assertEquals(new BigDecimal("100.00"), bankDao.getBalance(connection, "A"));
        assertEquals(new BigDecimal("0.00"), bankDao.getBalance(connection, "B"));
    }
}

