package com.signoraann.javalearning.lesson30;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.sql.*;

class BankServiceTest {
    private Connection connection;
    private BankDaoJdbc bankDao;

    @BeforeEach
    void createTestBase() throws SQLException {
        connection = DriverManager.getConnection("jdbc:h2:mem:bank_test;DB_CLOSE_DELAY=-1");
        bankDao = new BankDaoJdbc();
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                DROP TABLE IF EXISTS bank_account;
                CREATE TABLE bank_account
                (
                    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    account_name VARCHAR(20)      NOT NULL CHECK (account_name <> ''),
                    balance DOUBLE PRECISION NOT NULL CHECK ( balance >= 0 ),
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                );
                INSERT INTO bank_account (account_name, balance) VALUES ('A', 100.0), ('B', 0.0);
                """);
        }
    }

    @AfterEach
    void closeResources() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }

    @Test
    void testTransferMoneyTwiceHappyPath() {
        BankService bankService = new BankService(bankDao);
        bankService.transferMoney(connection, 25.5);
        bankService.transferMoney(connection, 25.5);
        assertEquals(51.0, bankDao.getBalance(connection, "B"));
    }

    @Test
    void testTransferMoneyFailureDoesNotLeaveTheConnectionInBrokenState() throws SQLException {
        BankService bankService = new BankService(bankDao);
        assertThrows(BankException.class, () -> bankService.transferMoney(connection, 500.0));
        assertEquals(100.0, bankDao.getBalance(connection, "A"));
        assertEquals(0.0, bankDao.getBalance(connection, "B"));
        assertTrue(connection.getAutoCommit());
        assertDoesNotThrow(() -> bankService.transferMoney(connection, 10));
    }
}
