package com.signoraann.javalearning.lesson28;

import com.signoraann.javalearning.lesson26.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.OffsetDateTime;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class UserDaoJdbcTest {
    private Connection connection;
    private UserDaoJdbc userDao;

    @BeforeEach
    void createTestBase() throws SQLException {
        connection = DriverManager.getConnection("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1");
        userDao = new UserDaoJdbc(connection);
        try (Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS users;\n" + "CREATE TABLE users\n"
                    + "(\n"
                    + "    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n"
                    + "    username   VARCHAR(50)  NOT NULL CHECK ( username <> '' ),\n"
                    + "    email      VARCHAR(100) NOT NULL UNIQUE CHECK ( email <> '' ),\n"
                    + "    age        INTEGER CHECK ( age > 0 ),\n"
                    + "    status     VARCHAR(20) DEFAULT 'active',\n"
                    + "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                    + ");");
        }
    }

    @Test
    void saveUserInDatabaseTest() throws SQLException {
        User user = new User(1L, "Dean", "diLaurentis@gmail.com", 26, OffsetDateTime.now());
        userDao.saveUserInDatabase(user);
        Optional<User> found = userDao.findUserById(1L);
        assertTrue(found.isPresent());
        assertEquals("Dean", found.get().username());
        assertEquals("diLaurentis@gmail.com", found.get().email());
        assertEquals(26, found.get().age());
    }

    @Test
    void findUserByIdTestReturnsEmptyOptionalObjectWhenUserNotFoundInDatabase() throws SQLException {
        Optional<User> notFoundUser = userDao.findUserById(999999L);
        assertTrue(notFoundUser.isEmpty());
    }
}
