package com.signoraann.javalearning.lesson28;

import com.signoraann.javalearning.lesson26.User;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.OffsetDateTime;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class UserDaoJdbcTest {
    private Connection connection;
    private UserDaoJdbc userDao;

    @BeforeEach
    void createTestBase() throws SQLException {
        connection = DriverManager.getConnection("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1");
        userDao = new UserDaoJdbc(connection);
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                DROP TABLE IF EXISTS users;
                CREATE TABLE users
                (
                    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username   VARCHAR(50)  NOT NULL CHECK ( username <> '' ),
                    email      VARCHAR(100) NOT NULL UNIQUE CHECK ( email <> '' ),
                    age        INTEGER CHECK ( age > 0 ),
                    status     VARCHAR(20) DEFAULT 'active',
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                );
                """);
        }
    }

    @AfterEach
    void closeResources() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }

    @Test
    void saveUserInDatabaseTest() {
        User user = new User(null, "Dean", "diLaurentis@gmail.com", 26);
        OffsetDateTime beforeSave = OffsetDateTime.now();
        userDao.saveUser(user);
        Optional<User> found = userDao.findUserById(1L);
        assertTrue(found.isPresent());
        assertEquals("Dean", found.get().username());
        assertEquals("diLaurentis@gmail.com", found.get().email());
        assertEquals(26, found.get().age());
        assertFalse(found.get().createdAt().isBefore(beforeSave));
    }

    @Test
    void findUserByIdTestReturnsEmptyOptionalObjectWhenUserNotFoundInDatabase() {
        Optional<User> notFoundUser = userDao.findUserById(999999L);
        assertTrue(notFoundUser.isEmpty());
    }

    @Test
    void testFindUserByUsernameHappyPath() {
        User user = new User(null, "Dean", "diLaurentis@gmail.com", 26);
        userDao.saveUser(user);
        Optional<User> found = userDao.findUserByUsername("Dean");
        assertTrue(found.isPresent());
        assertEquals("Dean", found.get().username());
    }

    @Test
    void testFindUserByUsernameWhenUserIsNotFoundReturnsEmptyOptionalObject() {
        assertTrue(userDao.findUserByUsername("Sam").isEmpty());
    }

    @Test
    void testDeleteByUsernameHappyPath() {
        User user = new User(null, "Dean", "diLaurentis@gmail.com", 26);
        userDao.saveUser(user);
        assertTrue(userDao.findUserByUsername("Dean").isPresent());
        userDao.deleteByUsername("Dean");
        assertFalse(userDao.findUserByUsername("Dean").isPresent());
    }
}
